### ISSUE TITLE
This project can be applied to VAE?

### ISSUE THREAD

**Issue by pandsia2007** [wpeebles/hessian_penalty#3]
This project can be applied to VAE?

**Comment by wpeebles** [comment]
Hi @pandsia2007. In principle it can be applied to VAEs. There are different ways you could go about it, but probably the most natural would be to apply the Hessian Penalty to the output of the decoder w.r.t. the input latent code. We haven't experimented much beyond applying it to GANs, though.

**Comment by pandsia2007** [comment]
Thank you very much.
